
import type { Category, CategoryWord } from './types';

// Palabras generales para modo clásico y con pista
// Las pistas son MUY VAGAS - una sola palabra genérica
export const GENERAL_WORDS: CategoryWord[] = [
  // Objetos cotidianos
  { word: "Paraguas", hint: "Agua" },
  { word: "Nevera", hint: "Casa" },
  { word: "Escalera", hint: "Vertical" },
  { word: "Espejo", hint: "Baño" },
  { word: "Almohada", hint: "Noche" },
  { word: "Microondas", hint: "Cocina" },
  { word: "Lámpara", hint: "Mesa" },
  { word: "Sofá", hint: "Descanso" },
  { word: "Lavadora", hint: "Blanco" },
  { word: "Televisión", hint: "Salón" },
  { word: "Ordenador", hint: "Trabajo" },
  { word: "Bicicleta", hint: "Verde" },
  { word: "Guitarra", hint: "Madera" },
  { word: "Reloj", hint: "Muñeca" },
  { word: "Gafas", hint: "Cara" },
  { word: "Mochila", hint: "Espalda" },
  { word: "Sartén", hint: "Metal" },
  { word: "Tijeras", hint: "Manos" },
  { word: "Martillo", hint: "Obra" },
  { word: "Cepillo", hint: "Mañana" },
  { word: "Cama", hint: "Habitación" },
  { word: "Ventana", hint: "Luz" },
  { word: "Puerta", hint: "Madera" },
  { word: "Llave", hint: "Metal" },
  { word: "Cartera", hint: "Bolsillo" },
  { word: "Móvil", hint: "Pantalla" },
  { word: "Auriculares", hint: "Música" },
  { word: "Cargador", hint: "Cable" },
  { word: "Toalla", hint: "Algodón" },
  { word: "Jabón", hint: "Agua" },
  { word: "Vela", hint: "Fuego" },
  { word: "Cuchillo", hint: "Cocina" },
  { word: "Tenedor", hint: "Mesa" },
  { word: "Cuchara", hint: "Sopa" },
  { word: "Plato", hint: "Redondo" },
  { word: "Vaso", hint: "Cristal" },
  { word: "Taza", hint: "Mañana" },
  { word: "Silla", hint: "Sentarse" },
  { word: "Mesa", hint: "Madera" },
  { word: "Alfombra", hint: "Suelo" },

  // Lugares
  { word: "Hospital", hint: "Blanco" },
  { word: "Aeropuerto", hint: "Maleta" },
  { word: "Biblioteca", hint: "Silencio" },
  { word: "Estadio", hint: "Gente" },
  { word: "Playa", hint: "Arena" },
  { word: "Montaña", hint: "Alto" },
  { word: "Museo", hint: "Arte" },
  { word: "Restaurante", hint: "Comida" },
  { word: "Supermercado", hint: "Carro" },
  { word: "Cine", hint: "Oscuro" },
  { word: "Parque", hint: "Verde" },
  { word: "Iglesia", hint: "Domingo" },
  { word: "Gimnasio", hint: "Sudor" },
  { word: "Discoteca", hint: "Noche" },
  { word: "Universidad", hint: "Jóvenes" },
  { word: "Gasolinera", hint: "Coche" },
  { word: "Farmacia", hint: "Salud" },
  { word: "Peluquería", hint: "Tijeras" },
  { word: "Hotel", hint: "Viaje" },
  { word: "Zoo", hint: "Jaula" },
  { word: "Banco", hint: "Dinero" },
  { word: "Oficina", hint: "Trabajo" },
  { word: "Cementerio", hint: "Flores" },
  { word: "Prisión", hint: "Rejas" },
  { word: "Circo", hint: "Carpa" },
  { word: "Teatro", hint: "Escenario" },
  { word: "Mercado", hint: "Fruta" },
  { word: "Puerto", hint: "Mar" },
  { word: "Estación", hint: "Tren" },
  { word: "Castillo", hint: "Piedra" },

  // Comida y bebida
  { word: "Pizza", hint: "Horno" },
  { word: "Hamburguesa", hint: "Carne" },
  { word: "Sushi", hint: "Crudo" },
  { word: "Paella", hint: "Domingo" },
  { word: "Chocolate", hint: "Dulce" },
  { word: "Cerveza", hint: "Bar" },
  { word: "Café", hint: "Negro" },
  { word: "Helado", hint: "Verano" },
  { word: "Tortilla", hint: "Sartén" },
  { word: "Pasta", hint: "Italia" },
  { word: "Ensalada", hint: "Verde" },
  { word: "Croissant", hint: "Mantequilla" },
  { word: "Vino", hint: "Botella" },
  { word: "Tarta", hint: "Velas" },
  { word: "Bocadillo", hint: "Pan" },
  { word: "Huevo", hint: "Gallina" },
  { word: "Leche", hint: "Vaca" },
  { word: "Arroz", hint: "Blanco" },
  { word: "Manzana", hint: "Roja" },
  { word: "Naranja", hint: "Zumo" },
  { word: "Plátano", hint: "Amarillo" },
  { word: "Fresa", hint: "Roja" },
  { word: "Sandía", hint: "Verde" },
  { word: "Queso", hint: "Ratón" },
  { word: "Pan", hint: "Horno" },

  // Animales
  { word: "Elefante", hint: "Grande" },
  { word: "Delfín", hint: "Agua" },
  { word: "Águila", hint: "Cielo" },
  { word: "Serpiente", hint: "Suelo" },
  { word: "Canguro", hint: "Salto" },
  { word: "Pingüino", hint: "Frío" },
  { word: "León", hint: "África" },
  { word: "Tiburón", hint: "Dientes" },
  { word: "Caballo", hint: "Campo" },
  { word: "Loro", hint: "Colores" },
  { word: "Tortuga", hint: "Lenta" },
  { word: "Jirafa", hint: "Alta" },
  { word: "Gorila", hint: "Negro" },
  { word: "Cocodrilo", hint: "Río" },
  { word: "Mariposa", hint: "Colores" },
  { word: "Perro", hint: "Casa" },
  { word: "Gato", hint: "Sofá" },
  { word: "Pájaro", hint: "Árbol" },
  { word: "Pez", hint: "Agua" },
  { word: "Araña", hint: "Tela" },
  { word: "Abeja", hint: "Miel" },
  { word: "Hormiga", hint: "Pequeña" },
  { word: "Rana", hint: "Verde" },
  { word: "Ratón", hint: "Pequeño" },
  { word: "Conejo", hint: "Orejas" },

  // Conceptos y eventos
  { word: "Boda", hint: "Blanco" },
  { word: "Cumpleaños", hint: "Velas" },
  { word: "Navidad", hint: "Invierno" },
  { word: "Halloween", hint: "Octubre" },
  { word: "Carnaval", hint: "Febrero" },
  { word: "Vacaciones", hint: "Verano" },
  { word: "Examen", hint: "Papel" },
  { word: "Entrevista", hint: "Nervios" },
  { word: "Concierto", hint: "Ruido" },
  { word: "Maratón", hint: "Correr" },
  { word: "Mudanza", hint: "Cajas" },
  { word: "Graduación", hint: "Gorro" },
  { word: "Divorcio", hint: "Abogado" },
  { word: "Jubilación", hint: "Mayor" },
  { word: "Lotería", hint: "Números" },
  { word: "Siesta", hint: "Tarde" },
  { word: "Resaca", hint: "Mañana" },
  { word: "Insomnio", hint: "Noche" },
  { word: "Pesadilla", hint: "Dormir" },
  { word: "Secreto", hint: "Oreja" },

  // Transporte
  { word: "Avión", hint: "Cielo" },
  { word: "Barco", hint: "Agua" },
  { word: "Tren", hint: "Vías" },
  { word: "Moto", hint: "Casco" },
  { word: "Autobús", hint: "Parada" },
  { word: "Taxi", hint: "Amarillo" },
  { word: "Metro", hint: "Túnel" },
  { word: "Helicóptero", hint: "Ruido" },
  { word: "Submarino", hint: "Profundo" },
  { word: "Cohete", hint: "Fuego" },
  { word: "Coche", hint: "Ruedas" },
  { word: "Patinete", hint: "Dos" },
  { word: "Ambulancia", hint: "Urgencia" },
  { word: "Camión", hint: "Grande" },
  { word: "Globo", hint: "Aire" },

  // Profesiones
  { word: "Bombero", hint: "Rojo" },
  { word: "Policía", hint: "Azul" },
  { word: "Médico", hint: "Blanco" },
  { word: "Profesor", hint: "Escuela" },
  { word: "Chef", hint: "Cocina" },
  { word: "Piloto", hint: "Avión" },
  { word: "Arquitecto", hint: "Edificio" },
  { word: "Abogado", hint: "Juicio" },
  { word: "Fotógrafo", hint: "Cámara" },
  { word: "Electricista", hint: "Cables" },
  { word: "Payaso", hint: "Circo" },
  { word: "Mago", hint: "Truco" },
  { word: "Espía", hint: "Secreto" },
  { word: "Pirata", hint: "Barco" },
  { word: "Astronauta", hint: "Espacio" },

  // Otros objetos y conceptos
  { word: "Diamante", hint: "Brillo" },
  { word: "Corona", hint: "Cabeza" },
  { word: "Espada", hint: "Metal" },
  { word: "Escudo", hint: "Defensa" },
  { word: "Bandera", hint: "País" },
  { word: "Moneda", hint: "Redonda" },
  { word: "Billete", hint: "Papel" },
  { word: "Carta", hint: "Sobre" },
  { word: "Libro", hint: "Papel" },
  { word: "Periódico", hint: "Diario" },
  { word: "Foto", hint: "Recuerdo" },
  { word: "Cuadro", hint: "Pared" },
  { word: "Estatua", hint: "Piedra" },
  { word: "Globo", hint: "Fiesta" },
  { word: "Pelota", hint: "Redonda" },
];

// Categorías con palabras específicas
export const CATEGORIES: Category[] = [
  {
    id: 'football',
    name: 'Fútbol',
    icon: '⚽',
    words: [
      // Jugadores actuales - pistas muy genéricas
      { word: "Messi", hint: "Bajo", subtype: "Jugador" },
      { word: "Cristiano Ronaldo", hint: "Salto", subtype: "Jugador" },
      { word: "Mbappé", hint: "Velocidad", subtype: "Jugador" },
      { word: "Haaland", hint: "Alto", subtype: "Jugador" },
      { word: "Vinicius Jr", hint: "Banda", subtype: "Jugador" },
      { word: "Bellingham", hint: "Joven", subtype: "Jugador" },
      { word: "De Bruyne", hint: "Pases", subtype: "Jugador" },
      { word: "Salah", hint: "Izquierda", subtype: "Jugador" },
      { word: "Lewandowski", hint: "Goles", subtype: "Jugador" },
      { word: "Neymar", hint: "Regates", subtype: "Jugador" },
      { word: "Modric", hint: "Centro", subtype: "Jugador" },
      { word: "Kroos", hint: "Precisión", subtype: "Jugador" },
      { word: "Kane", hint: "Goles", subtype: "Jugador" },
      { word: "Rodri", hint: "Pivote", subtype: "Jugador" },
      { word: "Pedri", hint: "Joven", subtype: "Jugador" },
      { word: "Gavi", hint: "Intenso", subtype: "Jugador" },
      { word: "Saka", hint: "Banda", subtype: "Jugador" },
      { word: "Yamal", hint: "Niño", subtype: "Jugador" },
      { word: "Son", hint: "Asia", subtype: "Jugador" },
      { word: "Griezmann", hint: "Rubio", subtype: "Jugador" },
      { word: "Benzema", hint: "Nueve", subtype: "Jugador" },
      { word: "Courtois", hint: "Alto", subtype: "Jugador" },
      { word: "Ter Stegen", hint: "Pies", subtype: "Jugador" },
      { word: "Alisson", hint: "Portero", subtype: "Jugador" },

      // Leyendas - pistas muy genéricas
      { word: "Maradona", hint: "Rizos", subtype: "Jugador" },
      { word: "Pelé", hint: "Rey", subtype: "Jugador" },
      { word: "Zidane", hint: "Calvo", subtype: "Jugador" },
      { word: "Ronaldinho", hint: "Dientes", subtype: "Jugador" },
      { word: "Beckham", hint: "Guapo", subtype: "Jugador" },
      { word: "Ronaldo Nazario", hint: "Gordo", subtype: "Jugador" },
      { word: "Iniesta", hint: "Calvo", subtype: "Jugador" },
      { word: "Xavi", hint: "Pases", subtype: "Jugador" },
      { word: "Buffon", hint: "Veterano", subtype: "Jugador" },
      { word: "Casillas", hint: "Bajo", subtype: "Jugador" },
      { word: "Pirlo", hint: "Barba", subtype: "Jugador" },
      { word: "Henry", hint: "Negro", subtype: "Jugador" },
      { word: "Raúl", hint: "Siete", subtype: "Jugador" },
      { word: "Roberto Carlos", hint: "Pierna", subtype: "Jugador" },
      { word: "Puyol", hint: "Pelo", subtype: "Jugador" },
      { word: "Ramos", hint: "Defensa", subtype: "Jugador" },
      { word: "Drogba", hint: "Fuerte", subtype: "Jugador" },
      { word: "Lampard", hint: "Goles", subtype: "Jugador" },
      { word: "Gerrard", hint: "Capitán", subtype: "Jugador" },
      { word: "Totti", hint: "Diez", subtype: "Jugador" },
      { word: "Del Piero", hint: "Diez", subtype: "Jugador" },
      { word: "Maldini", hint: "Defensa", subtype: "Jugador" },
      { word: "Cruyff", hint: "Catorce", subtype: "Jugador" },
      { word: "Baggio", hint: "Coleta", subtype: "Jugador" },
      { word: "Figo", hint: "Melena", subtype: "Jugador" },
      { word: "Kaká", hint: "Guapo", subtype: "Jugador" },
      { word: "Neuer", hint: "Loco", subtype: "Jugador" },
      { word: "Ibrahimovic", hint: "Nariz", subtype: "Jugador" },
      { word: "Rooney", hint: "Calvo", subtype: "Jugador" },
      { word: "Suárez", hint: "Dientes", subtype: "Jugador" },
      { word: "Cavani", hint: "Cabeza", subtype: "Jugador" },
      { word: "Agüero", hint: "Bajo", subtype: "Jugador" },
      { word: "Di María", hint: "Flaco", subtype: "Jugador" },

      // Equipos - pistas muy genéricas
      { word: "Real Madrid", hint: "Blanco", subtype: "Equipo" },
      { word: "Barcelona", hint: "Azulgrana", subtype: "Equipo" },
      { word: "Manchester United", hint: "Rojo", subtype: "Equipo" },
      { word: "Manchester City", hint: "Celeste", subtype: "Equipo" },
      { word: "Liverpool", hint: "Rojo", subtype: "Equipo" },
      { word: "Bayern Munich", hint: "Rojo", subtype: "Equipo" },
      { word: "PSG", hint: "Azul", subtype: "Equipo" },
      { word: "Juventus", hint: "Rayas", subtype: "Equipo" },
      { word: "Chelsea", hint: "Azul", subtype: "Equipo" },
      { word: "Arsenal", hint: "Rojo", subtype: "Equipo" },
      { word: "Atlético de Madrid", hint: "Rayas", subtype: "Equipo" },
      { word: "Inter de Milán", hint: "Rayas", subtype: "Equipo" },
      { word: "AC Milan", hint: "Rayas", subtype: "Equipo" },
      { word: "Borussia Dortmund", hint: "Amarillo", subtype: "Equipo" },
      { word: "Tottenham", hint: "Blanco", subtype: "Equipo" },
      { word: "Napoli", hint: "Celeste", subtype: "Equipo" },
      { word: "Ajax", hint: "Blanco", subtype: "Equipo" },
      { word: "Benfica", hint: "Rojo", subtype: "Equipo" },
      { word: "Porto", hint: "Azul", subtype: "Equipo" },
      { word: "Boca Juniors", hint: "Amarillo", subtype: "Equipo" },
      { word: "River Plate", hint: "Rojo", subtype: "Equipo" },
      { word: "Sevilla", hint: "Blanco", subtype: "Equipo" },
    ],
  },
  {
    id: 'movies',
    name: 'Películas',
    icon: '🎬',
    words: [
      { word: "Titanic", hint: "Agua" },
      { word: "El Padrino", hint: "Italia" },
      { word: "Matrix", hint: "Verde" },
      { word: "Star Wars", hint: "Espacio" },
      { word: "Jurassic Park", hint: "Isla" },
      { word: "Harry Potter", hint: "Gafas" },
      { word: "El Señor de los Anillos", hint: "Oro" },
      { word: "Gladiator", hint: "Arena" },
      { word: "Avatar", hint: "Azul" },
      { word: "Inception", hint: "Sueños" },
      { word: "Forrest Gump", hint: "Correr" },
      { word: "Pulp Fiction", hint: "Maleta" },
      { word: "El Rey León", hint: "África" },
      { word: "Toy Story", hint: "Juguetes" },
      { word: "Shrek", hint: "Verde" },
      { word: "Piratas del Caribe", hint: "Barco" },
      { word: "Indiana Jones", hint: "Sombrero" },
      { word: "Terminator", hint: "Robot" },
      { word: "Rocky", hint: "Boxeo" },
      { word: "E.T.", hint: "Dedo" },
      { word: "Tiburón", hint: "Mar" },
      { word: "Los Vengadores", hint: "Equipo" },
      { word: "Batman", hint: "Negro" },
      { word: "Spiderman", hint: "Rojo" },
      { word: "Iron Man", hint: "Metal" },
      { word: "Frozen", hint: "Hielo" },
      { word: "Coco", hint: "Guitarra" },
      { word: "Up", hint: "Globos" },
      { word: "Buscando a Nemo", hint: "Pez" },
      { word: "Ratatouille", hint: "Cocina" },
      { word: "Los Increíbles", hint: "Familia" },
      { word: "Fast & Furious", hint: "Coches" },
      { word: "John Wick", hint: "Perro" },
      { word: "Joker", hint: "Verde" },
      { word: "It", hint: "Globo" },
      { word: "Alien", hint: "Espacio" },
      { word: "Interstellar", hint: "Negro" },
      { word: "Fight Club", hint: "Golpes" },
      { word: "Sexto Sentido", hint: "Niño" },
      { word: "Regreso al Futuro", hint: "Coche" },
    ],
  },
  {
    id: 'music',
    name: 'Música',
    icon: '🎵',
    words: [
      { word: "Michael Jackson", hint: "Luna" },
      { word: "Madonna", hint: "Rubia" },
      { word: "Queen", hint: "Dientes" },
      { word: "The Beatles", hint: "Cuatro" },
      { word: "Elvis Presley", hint: "Tupé" },
      { word: "Bob Marley", hint: "Rastas" },
      { word: "Shakira", hint: "Caderas" },
      { word: "Beyoncé", hint: "Diva" },
      { word: "Taylor Swift", hint: "Rubia" },
      { word: "Ed Sheeran", hint: "Pelirrojo" },
      { word: "Adele", hint: "Voz" },
      { word: "Rihanna", hint: "Paraguas" },
      { word: "Drake", hint: "Barba" },
      { word: "Eminem", hint: "Rubio" },
      { word: "Kanye West", hint: "Ego" },
      { word: "Bad Bunny", hint: "Gafas" },
      { word: "Daddy Yankee", hint: "Latino" },
      { word: "Rosalía", hint: "Uñas" },
      { word: "Dua Lipa", hint: "Morena" },
      { word: "Bruno Mars", hint: "Bajo" },
      { word: "Lady Gaga", hint: "Rara" },
      { word: "Justin Bieber", hint: "Joven" },
      { word: "Ariana Grande", hint: "Coleta" },
      { word: "The Weeknd", hint: "Pelo" },
      { word: "Coldplay", hint: "Colores" },
      { word: "U2", hint: "Gafas" },
      { word: "Nirvana", hint: "Grunge" },
      { word: "AC/DC", hint: "Rayo" },
      { word: "Metallica", hint: "Negro" },
      { word: "Pink Floyd", hint: "Prisma" },
      { word: "Rolling Stones", hint: "Lengua" },
      { word: "BTS", hint: "Corea" },
      { word: "ABBA", hint: "Suecia" },
      { word: "Elton John", hint: "Gafas" },
      { word: "David Bowie", hint: "Ojos" },
      { word: "Prince", hint: "Morado" },
    ],
  },
  {
    id: 'food',
    name: 'Comida',
    icon: '🍔',
    words: [
      { word: "Pizza", hint: "Horno" },
      { word: "Hamburguesa", hint: "Pan" },
      { word: "Sushi", hint: "Crudo" },
      { word: "Tacos", hint: "Maíz" },
      { word: "Paella", hint: "Arroz" },
      { word: "Pasta", hint: "Agua" },
      { word: "Curry", hint: "Amarillo" },
      { word: "Kebab", hint: "Vertical" },
      { word: "Ramen", hint: "Caldo" },
      { word: "Croissant", hint: "Mantequilla" },
      { word: "Ceviche", hint: "Limón" },
      { word: "Burrito", hint: "Envuelto" },
      { word: "Hot Dog", hint: "Pan" },
      { word: "Tortilla Española", hint: "Huevo" },
      { word: "Gazpacho", hint: "Frío" },
      { word: "Jamón", hint: "Rosa" },
      { word: "Risotto", hint: "Cremoso" },
      { word: "Lasaña", hint: "Capas" },
      { word: "Tiramisú", hint: "Café" },
      { word: "Churros", hint: "Largo" },
      { word: "Helado", hint: "Frío" },
      { word: "Fondue", hint: "Derretido" },
      { word: "Hummus", hint: "Garbanzo" },
      { word: "Guacamole", hint: "Verde" },
      { word: "Croquetas", hint: "Frito" },
      { word: "Patatas Bravas", hint: "Picante" },
      { word: "Nachos", hint: "Crujiente" },
      { word: "Brownie", hint: "Chocolate" },
      { word: "Flan", hint: "Caramelo" },
      { word: "Palomitas", hint: "Maíz" },
    ],
  },
  {
    id: 'countries',
    name: 'Países',
    icon: '🌍',
    words: [
      { word: "España", hint: "Sol" },
      { word: "Francia", hint: "Torre" },
      { word: "Italia", hint: "Bota" },
      { word: "Alemania", hint: "Cerveza" },
      { word: "Inglaterra", hint: "Té" },
      { word: "Estados Unidos", hint: "Grande" },
      { word: "Brasil", hint: "Fútbol" },
      { word: "Argentina", hint: "Carne" },
      { word: "México", hint: "Picante" },
      { word: "Japón", hint: "Sushi" },
      { word: "China", hint: "Grande" },
      { word: "India", hint: "Especias" },
      { word: "Australia", hint: "Isla" },
      { word: "Canadá", hint: "Frío" },
      { word: "Rusia", hint: "Grande" },
      { word: "Egipto", hint: "Arena" },
      { word: "Grecia", hint: "Ruinas" },
      { word: "Portugal", hint: "Vecino" },
      { word: "Países Bajos", hint: "Plano" },
      { word: "Suiza", hint: "Montaña" },
      { word: "Suecia", hint: "Frío" },
      { word: "Noruega", hint: "Frío" },
      { word: "Irlanda", hint: "Verde" },
      { word: "Turquía", hint: "Puente" },
      { word: "Tailandia", hint: "Calor" },
      { word: "Corea del Sur", hint: "Tecnología" },
      { word: "Nueva Zelanda", hint: "Ovejas" },
      { word: "Colombia", hint: "Café" },
      { word: "Perú", hint: "Montaña" },
      { word: "Cuba", hint: "Isla" },
      { word: "Jamaica", hint: "Música" },
      { word: "Marruecos", hint: "Desierto" },
      { word: "Kenia", hint: "Safari" },
    ],
  },
  {
    id: 'animals',
    name: 'Animales',
    icon: '🦁',
    words: [
      { word: "León", hint: "Pelo" },
      { word: "Tigre", hint: "Rayas" },
      { word: "Elefante", hint: "Gris" },
      { word: "Jirafa", hint: "Manchas" },
      { word: "Cebra", hint: "Rayas" },
      { word: "Gorila", hint: "Negro" },
      { word: "Oso Polar", hint: "Blanco" },
      { word: "Oso Panda", hint: "China" },
      { word: "Lobo", hint: "Manada" },
      { word: "Zorro", hint: "Naranja" },
      { word: "Leopardo", hint: "Manchas" },
      { word: "Guepardo", hint: "Rápido" },
      { word: "Cocodrilo", hint: "Verde" },
      { word: "Serpiente", hint: "Largo" },
      { word: "Águila", hint: "Pico" },
      { word: "Búho", hint: "Noche" },
      { word: "Pingüino", hint: "Frío" },
      { word: "Flamenco", hint: "Rosa" },
      { word: "Loro", hint: "Colores" },
      { word: "Tiburón", hint: "Aleta" },
      { word: "Ballena", hint: "Grande" },
      { word: "Delfín", hint: "Salto" },
      { word: "Pulpo", hint: "Ocho" },
      { word: "Tortuga", hint: "Caparazón" },
      { word: "Canguro", hint: "Bolsa" },
      { word: "Koala", hint: "Árbol" },
      { word: "Camello", hint: "Joroba" },
      { word: "Murciélago", hint: "Noche" },
      { word: "Perro", hint: "Fiel" },
      { word: "Gato", hint: "Bigotes" },
    ],
  },
  {
    id: 'professions',
    name: 'Profesiones',
    icon: '👨‍⚕️',
    words: [
      { word: "Médico", hint: "Blanco" },
      { word: "Enfermero", hint: "Hospital" },
      { word: "Cirujano", hint: "Manos" },
      { word: "Dentista", hint: "Boca" },
      { word: "Abogado", hint: "Traje" },
      { word: "Juez", hint: "Negro" },
      { word: "Policía", hint: "Azul" },
      { word: "Bombero", hint: "Rojo" },
      { word: "Piloto", hint: "Avión" },
      { word: "Astronauta", hint: "Blanco" },
      { word: "Chef", hint: "Gorro" },
      { word: "Arquitecto", hint: "Planos" },
      { word: "Ingeniero", hint: "Cálculos" },
      { word: "Profesor", hint: "Tiza" },
      { word: "Científico", hint: "Bata" },
      { word: "Periodista", hint: "Micro" },
      { word: "Fotógrafo", hint: "Cámara" },
      { word: "Actor", hint: "Escenario" },
      { word: "Director", hint: "Silla" },
      { word: "Músico", hint: "Notas" },
      { word: "Cantante", hint: "Micro" },
      { word: "Bailarín", hint: "Pies" },
      { word: "Pintor", hint: "Pincel" },
      { word: "Escritor", hint: "Pluma" },
      { word: "Programador", hint: "Código" },
      { word: "Diseñador", hint: "Ratón" },
      { word: "Veterinario", hint: "Animales" },
      { word: "Psicólogo", hint: "Sofá" },
      { word: "Detective", hint: "Lupa" },
      { word: "Cartero", hint: "Cartas" },
    ],
  },
  {
    id: 'sports',
    name: 'Deportes',
    icon: '🏆',
    words: [
      { word: "Fútbol", hint: "Once" },
      { word: "Baloncesto", hint: "Alto" },
      { word: "Tenis", hint: "Red" },
      { word: "Golf", hint: "Hoyo" },
      { word: "Béisbol", hint: "Bate" },
      { word: "Rugby", hint: "Ovalado" },
      { word: "Hockey", hint: "Palo" },
      { word: "Voleibol", hint: "Red" },
      { word: "Natación", hint: "Agua" },
      { word: "Atletismo", hint: "Pista" },
      { word: "Ciclismo", hint: "Ruedas" },
      { word: "Boxeo", hint: "Guantes" },
      { word: "Karate", hint: "Blanco" },
      { word: "Judo", hint: "Suelo" },
      { word: "Gimnasia", hint: "Flexible" },
      { word: "Patinaje", hint: "Hielo" },
      { word: "Esquí", hint: "Nieve" },
      { word: "Surf", hint: "Olas" },
      { word: "Escalada", hint: "Roca" },
      { word: "Maratón", hint: "Largo" },
      { word: "Triatlón", hint: "Tres" },
      { word: "MMA", hint: "Jaula" },
      { word: "Esgrima", hint: "Espada" },
      { word: "Polo", hint: "Caballo" },
      { word: "Cricket", hint: "Bate" },
      { word: "Fútbol Americano", hint: "Casco" },
      { word: "Balonmano", hint: "Mano" },
      { word: "Ajedrez", hint: "Tablero" },
      { word: "Dardos", hint: "Diana" },
      { word: "Billar", hint: "Verde" },
    ],
  },
];

export function getRandomWord(mode: 'classic' | 'withHint' | 'categories', categoryId?: string): CategoryWord {
  if (mode === 'categories' && categoryId) {
    const category = CATEGORIES.find(c => c.id === categoryId);
    if (category && category.words.length > 0) {
      return category.words[Math.floor(Math.random() * category.words.length)];
    }
  }

  // Para classic y withHint usamos las palabras generales
  return GENERAL_WORDS[Math.floor(Math.random() * GENERAL_WORDS.length)];
}

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find(c => c.id === id);
}
