
import type { Category, CategoryWord } from './types';

// Palabras generales para modo clásico y con pista
// Las pistas son MUY VAGAS - una sola palabra genérica
export const GENERAL_WORDS: CategoryWord[] = [
  // Objetos cotidianos
  { word: "Paraguas", hint: "Agua" },
  { word: "Nevera", hint: "Casa" },
  { word: "Escalera", hint: "Vertical" },
  { word: "Espejo", hint: "Baño" },
  { word: "Almohada", hint: "Noche" },
  { word: "Microondas", hint: "Cocina" },
  { word: "Lámpara", hint: "Mesa" },
  { word: "Sofá", hint: "Descanso" },
  { word: "Lavadora", hint: "Blanco" },
  { word: "Televisión", hint: "Salón" },
  { word: "Ordenador", hint: "Trabajo" },
  { word: "Bicicleta", hint: "Verde" },
  { word: "Guitarra", hint: "Madera" },
  { word: "Reloj", hint: "Muñeca" },
  { word: "Gafas", hint: "Cara" },
  { word: "Mochila", hint: "Espalda" },
  { word: "Sartén", hint: "Metal" },
  { word: "Tijeras", hint: "Manos" },
  { word: "Martillo", hint: "Obra" },
  { word: "Cepillo", hint: "Mañana" },
  { word: "Cama", hint: "Habitación" },
  { word: "Ventana", hint: "Luz" },
  { word: "Puerta", hint: "Madera" },
  { word: "Llave", hint: "Metal" },
  { word: "Cartera", hint: "Bolsillo" },
  { word: "Móvil", hint: "Pantalla" },
  { word: "Auriculares", hint: "Música" },
  { word: "Cargador", hint: "Cable" },
  { word: "Toalla", hint: "Algodón" },
  { word: "Jabón", hint: "Agua" },
  { word: "Vela", hint: "Fuego" },
  { word: "Cuchillo", hint: "Cocina" },
  { word: "Tenedor", hint: "Mesa" },
  { word: "Cuchara", hint: "Sopa" },
  { word: "Plato", hint: "Redondo" },
  { word: "Vaso", hint: "Cristal" },
  { word: "Taza", hint: "Mañana" },
  { word: "Silla", hint: "Sentarse" },
  { word: "Mesa", hint: "Madera" },
  { word: "Alfombra", hint: "Suelo" },

  // Lugares
  { word: "Hospital", hint: "Blanco" },
  { word: "Aeropuerto", hint: "Maleta" },
  { word: "Biblioteca", hint: "Silencio" },
  { word: "Estadio", hint: "Gente" },
  { word: "Playa", hint: "Arena" },
  { word: "Montaña", hint: "Alto" },
  { word: "Museo", hint: "Arte" },
  { word: "Restaurante", hint: "Comida" },
  { word: "Supermercado", hint: "Carro" },
  { word: "Cine", hint: "Oscuro" },
  { word: "Parque", hint: "Verde" },
  { word: "Iglesia", hint: "Domingo" },
  { word: "Gimnasio", hint: "Sudor" },
  { word: "Discoteca", hint: "Noche" },
  { word: "Universidad", hint: "Jóvenes" },
  { word: "Gasolinera", hint: "Coche" },
  { word: "Farmacia", hint: "Salud" },
  { word: "Peluquería", hint: "Tijeras" },
  { word: "Hotel", hint: "Viaje" },
  { word: "Zoo", hint: "Jaula" },
  { word: "Banco", hint: "Dinero" },
  { word: "Oficina", hint: "Trabajo" },
  { word: "Cementerio", hint: "Flores" },
  { word: "Prisión", hint: "Rejas" },
  { word: "Circo", hint: "Carpa" },
  { word: "Teatro", hint: "Escenario" },
  { word: "Mercado", hint: "Fruta" },
  { word: "Puerto", hint: "Mar" },
  { word: "Estación", hint: "Tren" },
  { word: "Castillo", hint: "Piedra" },

  // Comida y bebida
  { word: "Pizza", hint: "Horno" },
  { word: "Hamburguesa", hint: "Carne" },
  { word: "Sushi", hint: "Crudo" },
  { word: "Paella", hint: "Domingo" },
  { word: "Chocolate", hint: "Dulce" },
  { word: "Cerveza", hint: "Bar" },
  { word: "Café", hint: "Negro" },
  { word: "Helado", hint: "Verano" },
  { word: "Tortilla", hint: "Sartén" },
  { word: "Pasta", hint: "Italia" },
  { word: "Ensalada", hint: "Verde" },
  { word: "Croissant", hint: "Mantequilla" },
  { word: "Vino", hint: "Botella" },
  { word: "Tarta", hint: "Velas" },
  { word: "Bocadillo", hint: "Pan" },
  { word: "Huevo", hint: "Gallina" },
  { word: "Leche", hint: "Vaca" },
  { word: "Arroz", hint: "Blanco" },
  { word: "Manzana", hint: "Roja" },
  { word: "Naranja", hint: "Zumo" },
  { word: "Plátano", hint: "Amarillo" },
  { word: "Fresa", hint: "Roja" },
  { word: "Sandía", hint: "Verde" },
  { word: "Queso", hint: "Ratón" },
  { word: "Pan", hint: "Horno" },

  // Animales
  { word: "Elefante", hint: "Grande" },
  { word: "Delfín", hint: "Agua" },
  { word: "Águila", hint: "Cielo" },
  { word: "Serpiente", hint: "Suelo" },
  { word: "Canguro", hint: "Salto" },
  { word: "Pingüino", hint: "Frío" },
  { word: "León", hint: "África" },
  { word: "Tiburón", hint: "Dientes" },
  { word: "Caballo", hint: "Campo" },
  { word: "Loro", hint: "Colores" },
  { word: "Tortuga", hint: "Lenta" },
  { word: "Jirafa", hint: "Alta" },
  { word: "Gorila", hint: "Negro" },
  { word: "Cocodrilo", hint: "Río" },
  { word: "Mariposa", hint: "Colores" },
  { word: "Perro", hint: "Casa" },
  { word: "Gato", hint: "Sofá" },
  { word: "Pájaro", hint: "Árbol" },
  { word: "Pez", hint: "Agua" },
  { word: "Araña", hint: "Tela" },
  { word: "Abeja", hint: "Miel" },
  { word: "Hormiga", hint: "Pequeña" },
  { word: "Rana", hint: "Verde" },
  { word: "Ratón", hint: "Pequeño" },
  { word: "Conejo", hint: "Orejas" },

  // Conceptos y eventos
  { word: "Boda", hint: "Blanco" },
  { word: "Cumpleaños", hint: "Velas" },
  { word: "Navidad", hint: "Invierno" },
  { word: "Halloween", hint: "Octubre" },
  { word: "Carnaval", hint: "Febrero" },
  { word: "Vacaciones", hint: "Verano" },
  { word: "Examen", hint: "Papel" },
  { word: "Entrevista", hint: "Nervios" },
  { word: "Concierto", hint: "Ruido" },
  { word: "Maratón", hint: "Correr" },
  { word: "Mudanza", hint: "Cajas" },
  { word: "Graduación", hint: "Gorro" },
  { word: "Divorcio", hint: "Abogado" },
  { word: "Jubilación", hint: "Mayor" },
  { word: "Lotería", hint: "Números" },
  { word: "Siesta", hint: "Tarde" },
  { word: "Resaca", hint: "Mañana" },
  { word: "Insomnio", hint: "Noche" },
  { word: "Pesadilla", hint: "Dormir" },
  { word: "Secreto", hint: "Oreja" },

  // Transporte
  { word: "Avión", hint: "Cielo" },
  { word: "Barco", hint: "Agua" },
  { word: "Tren", hint: "Vías" },
  { word: "Moto", hint: "Casco" },
  { word: "Autobús", hint: "Parada" },
  { word: "Taxi", hint: "Amarillo" },
  { word: "Metro", hint: "Túnel" },
  { word: "Helicóptero", hint: "Ruido" },
  { word: "Submarino", hint: "Profundo" },
  { word: "Cohete", hint: "Fuego" },
  { word: "Coche", hint: "Ruedas" },
  { word: "Patinete", hint: "Dos" },
  { word: "Ambulancia", hint: "Urgencia" },
  { word: "Camión", hint: "Grande" },
  { word: "Globo", hint: "Aire" },

  // Profesiones
  { word: "Bombero", hint: "Rojo" },
  { word: "Policía", hint: "Azul" },
  { word: "Médico", hint: "Blanco" },
  { word: "Profesor", hint: "Escuela" },
  { word: "Chef", hint: "Cocina" },
  { word: "Piloto", hint: "Avión" },
  { word: "Arquitecto", hint: "Edificio" },
  { word: "Abogado", hint: "Juicio" },
  { word: "Fotógrafo", hint: "Cámara" },
  { word: "Electricista", hint: "Cables" },
  { word: "Payaso", hint: "Circo" },
  { word: "Mago", hint: "Truco" },
  { word: "Espía", hint: "Secreto" },
  { word: "Pirata", hint: "Barco" },
  { word: "Astronauta", hint: "Espacio" },

  // Otros objetos y conceptos
  { word: "Diamante", hint: "Brillo" },
  { word: "Corona", hint: "Cabeza" },
  { word: "Espada", hint: "Metal" },
  { word: "Escudo", hint: "Defensa" },
  { word: "Bandera", hint: "País" },
  { word: "Moneda", hint: "Redonda" },
  { word: "Billete", hint: "Papel" },
  { word: "Carta", hint: "Sobre" },
  { word: "Libro", hint: "Papel" },
  { word: "Periódico", hint: "Diario" },
  { word: "Foto", hint: "Recuerdo" },
  { word: "Cuadro", hint: "Pared" },
  { word: "Estatua", hint: "Piedra" },
  { word: "Globo", hint: "Fiesta" },
  { word: "Pelota", hint: "Redonda" },

  // Nuevas palabras - Objetos
  { word: "Paraguas", hint: "Lluvia" },
  { word: "Brújula", hint: "Norte" },
  { word: "Linterna", hint: "Pilas" },
  { word: "Termómetro", hint: "Fiebre" },
  { word: "Calculadora", hint: "Números" },
  { word: "Despertador", hint: "Mañana" },
  { word: "Impresora", hint: "Papel" },
  { word: "Aspiradora", hint: "Ruido" },
  { word: "Secador", hint: "Aire" },
  { word: "Plancha", hint: "Ropa" },

  // Nuevas palabras - Naturaleza
  { word: "Volcán", hint: "Lava" },
  { word: "Arcoíris", hint: "Colores" },
  { word: "Relámpago", hint: "Luz" },
  { word: "Tsunami", hint: "Ola" },
  { word: "Tornado", hint: "Viento" },
  { word: "Glaciar", hint: "Hielo" },
  { word: "Desierto", hint: "Arena" },
  { word: "Cascada", hint: "Agua" },
  { word: "Cueva", hint: "Oscuro" },
  { word: "Bosque", hint: "Árboles" },

  // Nuevas palabras - Instrumentos
  { word: "Piano", hint: "Teclas" },
  { word: "Violín", hint: "Arco" },
  { word: "Batería", hint: "Baquetas" },
  { word: "Flauta", hint: "Soplar" },
  { word: "Trompeta", hint: "Latón" },
  { word: "Saxofón", hint: "Jazz" },
  { word: "Arpa", hint: "Cuerdas" },
  { word: "Acordeón", hint: "Fuelle" },
  { word: "Tambor", hint: "Golpe" },
  { word: "Pandereta", hint: "Mano" },

  // Nuevas palabras - Ropa y accesorios
  { word: "Corbata", hint: "Cuello" },
  { word: "Cinturón", hint: "Hebilla" },
  { word: "Bufanda", hint: "Invierno" },
  { word: "Guantes", hint: "Dedos" },
  { word: "Sombrero", hint: "Cabeza" },
  { word: "Zapatillas", hint: "Deporte" },
  { word: "Pijama", hint: "Dormir" },
  { word: "Bañador", hint: "Playa" },
  { word: "Pendientes", hint: "Orejas" },
  { word: "Pulsera", hint: "Muñeca" },

  // Nuevas palabras - Juegos y entretenimiento
  { word: "Dominó", hint: "Fichas" },
  { word: "Parchís", hint: "Dados" },
  { word: "Ruleta", hint: "Gira" },
  { word: "Cometa", hint: "Viento" },
  { word: "Yoyó", hint: "Cuerda" },
  { word: "Puzle", hint: "Piezas" },
  { word: "Karaoke", hint: "Cantar" },
  { word: "Videojuego", hint: "Mando" },
  { word: "Muñeca", hint: "Juguete" },
  { word: "Peluche", hint: "Suave" },

  // Nuevas palabras - Tecnología
  { word: "Tablet", hint: "Pantalla" },
  { word: "Drone", hint: "Vuela" },
  { word: "Robot", hint: "Metal" },
  { word: "Satélite", hint: "Espacio" },
  { word: "Radar", hint: "Ondas" },
  { word: "USB", hint: "Puerto" },
  { word: "Wifi", hint: "Internet" },
  { word: "Bluetooth", hint: "Azul" },
  { word: "GPS", hint: "Ubicación" },
  { word: "Webcam", hint: "Vídeo" },

  // Nuevas palabras - Deportes y actividades
  { word: "Raqueta", hint: "Tenis" },
  { word: "Balón", hint: "Redondo" },
  { word: "Patines", hint: "Ruedas" },
  { word: "Esquís", hint: "Nieve" },
  { word: "Pesas", hint: "Gimnasio" },
  { word: "Cuerda", hint: "Saltar" },
  { word: "Red", hint: "Pesca" },
  { word: "Anzuelo", hint: "Pez" },
  { word: "Tienda", hint: "Camping" },
  { word: "Saco", hint: "Dormir" },

  // Nuevas palabras - Naturaleza y clima
  { word: "Nube", hint: "Blanca" },
  { word: "Luna", hint: "Noche" },
  { word: "Sol", hint: "Calor" },
  { word: "Estrella", hint: "Brilla" },
  { word: "Río", hint: "Agua" },
  { word: "Lago", hint: "Peces" },
  { word: "Océano", hint: "Salado" },
  { word: "Isla", hint: "Agua" },
  { word: "Selva", hint: "Verde" },
  { word: "Pradera", hint: "Hierba" },

  // Nuevas palabras - Casa y hogar
  { word: "Chimenea", hint: "Fuego" },
  { word: "Balcón", hint: "Vista" },
  { word: "Garaje", hint: "Coche" },
  { word: "Sótano", hint: "Bajo" },
  { word: "Ático", hint: "Alto" },
  { word: "Jardín", hint: "Plantas" },
  { word: "Piscina", hint: "Agua" },
  { word: "Terraza", hint: "Exterior" },
  { word: "Cocina", hint: "Comida" },
  { word: "Baño", hint: "Agua" },

  // Nuevas palabras - Cuerpo y salud
  { word: "Corazón", hint: "Late" },
  { word: "Cerebro", hint: "Piensa" },
  { word: "Pulmón", hint: "Aire" },
  { word: "Estómago", hint: "Hambre" },
  { word: "Músculo", hint: "Fuerza" },
  { word: "Hueso", hint: "Duro" },
  { word: "Sangre", hint: "Roja" },
  { word: "Diente", hint: "Boca" },
  { word: "Uña", hint: "Dedo" },
  { word: "Pelo", hint: "Cabeza" },

  // Nuevas palabras - Miscelánea
  { word: "Calendario", hint: "Pared" },
  { word: "Diccionario", hint: "Palabras" },
  { word: "Enciclopedia", hint: "Saber" },
  { word: "Microscopio", hint: "Pequeño" },
  { word: "Telescopio", hint: "Estrellas" },
  { word: "Binoculares", hint: "Lejos" },
  { word: "Extintor", hint: "Rojo" },
  { word: "Candado", hint: "Cerrar" },
  { word: "Cenicero", hint: "Humo" },
  { word: "Florero", hint: "Agua" },

  // Nuevas palabras - Herramientas
  { word: "Destornillador", hint: "Girar" },
  { word: "Taladro", hint: "Agujero" },
  { word: "Serrucho", hint: "Cortar" },
  { word: "Llave inglesa", hint: "Tuerca" },
  { word: "Alicates", hint: "Apretar" },
  { word: "Cinta métrica", hint: "Medir" },
  { word: "Nivel", hint: "Recto" },
  { word: "Brocha", hint: "Pintar" },
  { word: "Rodillo", hint: "Pared" },
  { word: "Escalera", hint: "Subir" },

  // Nuevas palabras - Naturaleza y jardín
  { word: "Maceta", hint: "Planta" },
  { word: "Regadera", hint: "Agua" },
  { word: "Tijeras de podar", hint: "Cortar" },
  { word: "Rastrillo", hint: "Hojas" },
  { word: "Pala", hint: "Cavar" },
  { word: "Carretilla", hint: "Rueda" },
  { word: "Semilla", hint: "Crecer" },
  { word: "Abono", hint: "Tierra" },
  { word: "Césped", hint: "Verde" },
  { word: "Rocío", hint: "Mañana" },

  // Nuevas palabras - Oficina y escuela
  { word: "Grapadora", hint: "Metal" },
  { word: "Perforadora", hint: "Agujero" },
  { word: "Carpeta", hint: "Papeles" },
  { word: "Archivador", hint: "Orden" },
  { word: "Pizarra", hint: "Tiza" },
  { word: "Proyector", hint: "Imagen" },
  { word: "Rotulador", hint: "Color" },
  { word: "Compás", hint: "Círculo" },
  { word: "Escuadra", hint: "Ángulo" },
  { word: "Transportador", hint: "Grados" },

  // Nuevas palabras - Electrónica
  { word: "Altavoz", hint: "Sonido" },
  { word: "Micrófono", hint: "Voz" },
  { word: "Control remoto", hint: "Botones" },
  { word: "Batería", hint: "Energía" },
  { word: "Enchufe", hint: "Pared" },
  { word: "Interruptor", hint: "Luz" },
  { word: "Bombilla", hint: "Filamento" },
  { word: "Ventilador", hint: "Aire" },
  { word: "Aire acondicionado", hint: "Frío" },
  { word: "Radiador", hint: "Calor" },

  // Palabras divertidas - Familia y relaciones
  { word: "Suegra", hint: "Familia" },
  { word: "Cuñado", hint: "Navidad" },
  { word: "Ex", hint: "Pasado" },
  { word: "Crush", hint: "Secreto" },
  { word: "Friendzone", hint: "Dolor" },
  { word: "Tinder", hint: "Deslizar" },
  { word: "Boda", hint: "Caro" },
  { word: "Divorcio", hint: "Abogado" },
  { word: "Bebé", hint: "Llanto" },
  { word: "Adolescente", hint: "Drama" },

  // Palabras divertidas - Situaciones incómodas
  { word: "Pedo", hint: "Sonido" },
  { word: "Eructo", hint: "Gas" },
  { word: "Ronquido", hint: "Noche" },
  { word: "Resaca", hint: "Domingo" },
  { word: "Cruda", hint: "Arrepentimiento" },
  { word: "Vómito", hint: "Mareo" },
  { word: "Diarrea", hint: "Urgencia" },
  { word: "Granos", hint: "Cara" },
  { word: "Caspa", hint: "Hombros" },
  { word: "Sudor", hint: "Verano" },

  // Palabras divertidas - Cosas random
  { word: "Calvo", hint: "Brillo" },
  { word: "Peluca", hint: "Falso" },
  { word: "Bigote", hint: "Años 80" },
  { word: "Moño", hint: "Abuela" },
  { word: "Tanga", hint: "Playa" },
  { word: "Calcetines", hint: "Regalo" },
  { word: "Chanclas", hint: "Padre" },
  { word: "Crocs", hint: "Feo" },
  { word: "Fanny pack", hint: "Turista" },
  { word: "Mullet", hint: "Pelo" },

  // Palabras divertidas - Comida graciosa
  { word: "Kebab", hint: "Noche" },
  { word: "Churros", hint: "Madrugada" },
  { word: "Sobras", hint: "Tupper" },
  { word: "Microondas", hint: "Soltero" },
  { word: "Ramen instantáneo", hint: "Estudiante" },
  { word: "All you can eat", hint: "Reto" },
  { word: "Picante", hint: "Arrepentimiento" },
  { word: "Ajo", hint: "Aliento" },
  { word: "Cebolla", hint: "Lágrimas" },
  { word: "Café solo", hint: "Lunes" },

  // Palabras divertidas - Vida moderna
  { word: "WiFi", hint: "Necesidad" },
  { word: "Batería baja", hint: "Pánico" },
  { word: "Lunes", hint: "Depresión" },
  { word: "Viernes", hint: "Alegría" },
  { word: "Alarma", hint: "Odio" },
  { word: "Atasco", hint: "Rabia" },
  { word: "IKEA", hint: "Pelea" },
  { word: "Black Friday", hint: "Locura" },
  { word: "Gimnasio enero", hint: "Mentira" },
  { word: "Dieta", hint: "Lunes" },
];

// Categorías con palabras específicas
export const CATEGORIES: Category[] = [
  {
    id: 'football',
    name: 'Fútbol',
    icon: '⚽',
    words: [
      // Jugadores actuales - pistas muy genéricas
      { word: "Messi", hint: "Bajo", subtype: "Jugador" },
      { word: "Cristiano Ronaldo", hint: "Salto", subtype: "Jugador" },
      { word: "Mbappé", hint: "Velocidad", subtype: "Jugador" },
      { word: "Haaland", hint: "Alto", subtype: "Jugador" },
      { word: "Vinicius Jr", hint: "Banda", subtype: "Jugador" },
      { word: "Bellingham", hint: "Joven", subtype: "Jugador" },
      { word: "De Bruyne", hint: "Pases", subtype: "Jugador" },
      { word: "Salah", hint: "Izquierda", subtype: "Jugador" },
      { word: "Lewandowski", hint: "Goles", subtype: "Jugador" },
      { word: "Neymar", hint: "Regates", subtype: "Jugador" },
      { word: "Modric", hint: "Centro", subtype: "Jugador" },
      { word: "Kroos", hint: "Precisión", subtype: "Jugador" },
      { word: "Kane", hint: "Goles", subtype: "Jugador" },
      { word: "Rodri", hint: "Pivote", subtype: "Jugador" },
      { word: "Pedri", hint: "Joven", subtype: "Jugador" },
      { word: "Gavi", hint: "Intenso", subtype: "Jugador" },
      { word: "Saka", hint: "Banda", subtype: "Jugador" },
      { word: "Yamal", hint: "Niño", subtype: "Jugador" },
      { word: "Son", hint: "Asia", subtype: "Jugador" },
      { word: "Griezmann", hint: "Rubio", subtype: "Jugador" },
      { word: "Benzema", hint: "Nueve", subtype: "Jugador" },
      { word: "Courtois", hint: "Alto", subtype: "Jugador" },
      { word: "Ter Stegen", hint: "Pies", subtype: "Jugador" },
      { word: "Alisson", hint: "Portero", subtype: "Jugador" },

      // Leyendas - pistas muy genéricas
      { word: "Maradona", hint: "Rizos", subtype: "Jugador" },
      { word: "Pelé", hint: "Rey", subtype: "Jugador" },
      { word: "Zidane", hint: "Calvo", subtype: "Jugador" },
      { word: "Ronaldinho", hint: "Dientes", subtype: "Jugador" },
      { word: "Beckham", hint: "Guapo", subtype: "Jugador" },
      { word: "Ronaldo Nazario", hint: "Gordo", subtype: "Jugador" },
      { word: "Iniesta", hint: "Calvo", subtype: "Jugador" },
      { word: "Xavi", hint: "Pases", subtype: "Jugador" },
      { word: "Buffon", hint: "Veterano", subtype: "Jugador" },
      { word: "Casillas", hint: "Bajo", subtype: "Jugador" },
      { word: "Pirlo", hint: "Barba", subtype: "Jugador" },
      { word: "Henry", hint: "Negro", subtype: "Jugador" },
      { word: "Raúl", hint: "Siete", subtype: "Jugador" },
      { word: "Roberto Carlos", hint: "Pierna", subtype: "Jugador" },
      { word: "Puyol", hint: "Pelo", subtype: "Jugador" },
      { word: "Ramos", hint: "Defensa", subtype: "Jugador" },
      { word: "Drogba", hint: "Fuerte", subtype: "Jugador" },
      { word: "Lampard", hint: "Goles", subtype: "Jugador" },
      { word: "Gerrard", hint: "Capitán", subtype: "Jugador" },
      { word: "Totti", hint: "Diez", subtype: "Jugador" },
      { word: "Del Piero", hint: "Diez", subtype: "Jugador" },
      { word: "Maldini", hint: "Defensa", subtype: "Jugador" },
      { word: "Cruyff", hint: "Catorce", subtype: "Jugador" },
      { word: "Baggio", hint: "Coleta", subtype: "Jugador" },
      { word: "Figo", hint: "Melena", subtype: "Jugador" },
      { word: "Kaká", hint: "Guapo", subtype: "Jugador" },
      { word: "Neuer", hint: "Loco", subtype: "Jugador" },
      { word: "Ibrahimovic", hint: "Nariz", subtype: "Jugador" },
      { word: "Rooney", hint: "Calvo", subtype: "Jugador" },
      { word: "Suárez", hint: "Dientes", subtype: "Jugador" },
      { word: "Cavani", hint: "Cabeza", subtype: "Jugador" },
      { word: "Agüero", hint: "Bajo", subtype: "Jugador" },
      { word: "Di María", hint: "Flaco", subtype: "Jugador" },

      // Equipos - pistas muy genéricas
      { word: "Real Madrid", hint: "Blanco", subtype: "Equipo" },
      { word: "Barcelona", hint: "Azulgrana", subtype: "Equipo" },
      { word: "Manchester United", hint: "Rojo", subtype: "Equipo" },
      { word: "Manchester City", hint: "Celeste", subtype: "Equipo" },
      { word: "Liverpool", hint: "Rojo", subtype: "Equipo" },
      { word: "Bayern Munich", hint: "Rojo", subtype: "Equipo" },
      { word: "PSG", hint: "Azul", subtype: "Equipo" },
      { word: "Juventus", hint: "Rayas", subtype: "Equipo" },
      { word: "Chelsea", hint: "Azul", subtype: "Equipo" },
      { word: "Arsenal", hint: "Rojo", subtype: "Equipo" },
      { word: "Atlético de Madrid", hint: "Rayas", subtype: "Equipo" },
      { word: "Inter de Milán", hint: "Rayas", subtype: "Equipo" },
      { word: "AC Milan", hint: "Rayas", subtype: "Equipo" },
      { word: "Borussia Dortmund", hint: "Amarillo", subtype: "Equipo" },
      { word: "Tottenham", hint: "Blanco", subtype: "Equipo" },
      { word: "Napoli", hint: "Celeste", subtype: "Equipo" },
      { word: "Ajax", hint: "Blanco", subtype: "Equipo" },
      { word: "Benfica", hint: "Rojo", subtype: "Equipo" },
      { word: "Porto", hint: "Azul", subtype: "Equipo" },
      { word: "Boca Juniors", hint: "Amarillo", subtype: "Equipo" },
      { word: "River Plate", hint: "Rojo", subtype: "Equipo" },
      { word: "Sevilla", hint: "Blanco", subtype: "Equipo" },

      // Nuevos jugadores
      { word: "Vinícius Júnior", hint: "Rápido", subtype: "Jugador" },
      { word: "Kylian Mbappé", hint: "Joven", subtype: "Jugador" },
      { word: "Rashford", hint: "Inglés", subtype: "Jugador" },
      { word: "Foden", hint: "Rubio", subtype: "Jugador" },
      { word: "Florian Wirtz", hint: "Alemán", subtype: "Jugador" },
      { word: "Jamal Musiala", hint: "Joven", subtype: "Jugador" },
      { word: "Tchouaméni", hint: "Alto", subtype: "Jugador" },
      { word: "Valverde", hint: "Motor", subtype: "Jugador" },
      { word: "Camavinga", hint: "Francés", subtype: "Jugador" },
      { word: "Militão", hint: "Brasileño", subtype: "Jugador" },
      { word: "Rüdiger", hint: "Alemán", subtype: "Jugador" },
      { word: "Van Dijk", hint: "Alto", subtype: "Jugador" },
      { word: "Kimmich", hint: "Versátil", subtype: "Jugador" },
      { word: "Müller", hint: "Goles", subtype: "Jugador" },
      { word: "Sané", hint: "Rápido", subtype: "Jugador" },
      { word: "Gündogan", hint: "Capitán", subtype: "Jugador" },
      { word: "Szczesny", hint: "Portero", subtype: "Jugador" },
      { word: "Donnarumma", hint: "Alto", subtype: "Jugador" },
      { word: "Oblak", hint: "Portero", subtype: "Jugador" },
      { word: "Navas", hint: "Costarricense", subtype: "Jugador" },
      { word: "Carvajal", hint: "Lateral", subtype: "Jugador" },
      { word: "Alba", hint: "Izquierda", subtype: "Jugador" },
      { word: "Busquets", hint: "Pivote", subtype: "Jugador" },
      { word: "Koke", hint: "Capitán", subtype: "Jugador" },
      { word: "Morata", hint: "Alto", subtype: "Jugador" },
      { word: "Oyarzabal", hint: "Vasco", subtype: "Jugador" },
      { word: "Ferran Torres", hint: "Valencia", subtype: "Jugador" },
      { word: "Ansu Fati", hint: "Lesiones", subtype: "Jugador" },
      { word: "Raphinha", hint: "Brasileño", subtype: "Jugador" },

      // Nuevos equipos
      { word: "Valencia", hint: "Murciélago", subtype: "Equipo" },
      { word: "Real Sociedad", hint: "Vasco", subtype: "Equipo" },
      { word: "Athletic Bilbao", hint: "Vasco", subtype: "Equipo" },
      { word: "Villarreal", hint: "Amarillo", subtype: "Equipo" },
      { word: "Real Betis", hint: "Verde", subtype: "Equipo" },
      { word: "Aston Villa", hint: "Claret", subtype: "Equipo" },
      { word: "Newcastle", hint: "Negro", subtype: "Equipo" },
      { word: "West Ham", hint: "Claret", subtype: "Equipo" },
      { word: "Everton", hint: "Azul", subtype: "Equipo" },
      { word: "Leicester", hint: "Azul", subtype: "Equipo" },
      { word: "Wolverhampton", hint: "Naranja", subtype: "Equipo" },
      { word: "RB Leipzig", hint: "Rojo", subtype: "Equipo" },
      { word: "Bayer Leverkusen", hint: "Rojo", subtype: "Equipo" },
      { word: "Schalke 04", hint: "Azul", subtype: "Equipo" },
      { word: "Olympique Lyon", hint: "Blanco", subtype: "Equipo" },
      { word: "Olympique Marsella", hint: "Blanco", subtype: "Equipo" },
      { word: "AS Monaco", hint: "Rojo", subtype: "Equipo" },
      { word: "Sporting Lisboa", hint: "Verde", subtype: "Equipo" },
      { word: "Feyenoord", hint: "Rojo", subtype: "Equipo" },
      { word: "PSV Eindhoven", hint: "Rojo", subtype: "Equipo" },
    ],
  },
  {
    id: 'movies',
    name: 'Películas',
    icon: '🎬',
    words: [
      { word: "Titanic", hint: "Agua" },
      { word: "El Padrino", hint: "Italia" },
      { word: "Matrix", hint: "Verde" },
      { word: "Star Wars", hint: "Espacio" },
      { word: "Jurassic Park", hint: "Isla" },
      { word: "Harry Potter", hint: "Gafas" },
      { word: "El Señor de los Anillos", hint: "Oro" },
      { word: "Gladiator", hint: "Arena" },
      { word: "Avatar", hint: "Azul" },
      { word: "Inception", hint: "Sueños" },
      { word: "Forrest Gump", hint: "Correr" },
      { word: "Pulp Fiction", hint: "Maleta" },
      { word: "El Rey León", hint: "África" },
      { word: "Toy Story", hint: "Juguetes" },
      { word: "Shrek", hint: "Verde" },
      { word: "Piratas del Caribe", hint: "Barco" },
      { word: "Indiana Jones", hint: "Sombrero" },
      { word: "Terminator", hint: "Robot" },
      { word: "Rocky", hint: "Boxeo" },
      { word: "E.T.", hint: "Dedo" },
      { word: "Tiburón", hint: "Mar" },
      { word: "Los Vengadores", hint: "Equipo" },
      { word: "Batman", hint: "Negro" },
      { word: "Spiderman", hint: "Rojo" },
      { word: "Iron Man", hint: "Metal" },
      { word: "Frozen", hint: "Hielo" },
      { word: "Coco", hint: "Guitarra" },
      { word: "Up", hint: "Globos" },
      { word: "Buscando a Nemo", hint: "Pez" },
      { word: "Ratatouille", hint: "Cocina" },
      { word: "Los Increíbles", hint: "Familia" },
      { word: "Fast & Furious", hint: "Coches" },
      { word: "John Wick", hint: "Perro" },
      { word: "Joker", hint: "Verde" },
      { word: "It", hint: "Globo" },
      { word: "Alien", hint: "Espacio" },
      { word: "Interstellar", hint: "Negro" },
      { word: "Fight Club", hint: "Golpes" },
      { word: "Sexto Sentido", hint: "Niño" },
      { word: "Regreso al Futuro", hint: "Coche" },

      // Nuevas películas
      { word: "El Club de la Lucha", hint: "Jabón" },
      { word: "Scarface", hint: "Cocaína" },
      { word: "Casino", hint: "Vegas" },
      { word: "Goodfellas", hint: "Mafia" },
      { word: "El Resplandor", hint: "Hotel" },
      { word: "Psicosis", hint: "Ducha" },
      { word: "Los Goonies", hint: "Tesoro" },
      { word: "Gremlins", hint: "Agua" },
      { word: "Ghostbusters", hint: "Fantasmas" },
      { word: "Top Gun", hint: "Avión" },
      { word: "Dirty Dancing", hint: "Baile" },
      { word: "Grease", hint: "Coche" },
      { word: "Pretty Woman", hint: "Rojo" },
      { word: "Notting Hill", hint: "Londres" },
      { word: "Love Actually", hint: "Navidad" },
      { word: "El Diario de Bridget Jones", hint: "Diario" },
      { word: "El Diablo Viste de Prada", hint: "Moda" },
      { word: "Mean Girls", hint: "Instituto" },
      { word: "Clueless", hint: "Rubia" },
      { word: "American Pie", hint: "Tarta" },
      { word: "Resacón en Las Vegas", hint: "Tigre" },
      { word: "Superbad", hint: "Fiesta" },
      { word: "Juno", hint: "Embarazo" },
      { word: "500 Días Juntos", hint: "Amor" },
      { word: "La La Land", hint: "Musical" },
      { word: "Whiplash", hint: "Batería" },
      { word: "El Gran Lebowski", hint: "Bolos" },
      { word: "Fargo", hint: "Nieve" },
      { word: "Sin City", hint: "Negro" },
      { word: "Kill Bill", hint: "Espada" },
      { word: "Django", hint: "Western" },
      { word: "Malditos Bastardos", hint: "Guerra" },
      { word: "El Pianista", hint: "Piano" },
      { word: "La Lista de Schindler", hint: "Guerra" },
      { word: "Salvar al Soldado Ryan", hint: "Playa" },
      { word: "Apocalypse Now", hint: "Helicóptero" },
      { word: "Full Metal Jacket", hint: "Casco" },
      { word: "Platoon", hint: "Selva" },
      { word: "Blade Runner", hint: "Lluvia" },
      { word: "Mad Max", hint: "Desierto" },
      { word: "Dune", hint: "Arena" },
      { word: "El Quinto Elemento", hint: "Naranja" },
      { word: "Men in Black", hint: "Negro" },
      { word: "Independence Day", hint: "Aliens" },
      { word: "Gravity", hint: "Espacio" },
      { word: "The Martian", hint: "Marte" },
      { word: "Wall-E", hint: "Robot" },
      { word: "Monsters Inc", hint: "Monstruos" },
      { word: "Cars", hint: "Coches" },
      { word: "Moana", hint: "Mar" },
      { word: "Encanto", hint: "Colombia" },
    ],
  },
  {
    id: 'music',
    name: 'Música',
    icon: '🎵',
    words: [
      { word: "Michael Jackson", hint: "Luna" },
      { word: "Madonna", hint: "Rubia" },
      { word: "Queen", hint: "Dientes" },
      { word: "The Beatles", hint: "Cuatro" },
      { word: "Elvis Presley", hint: "Tupé" },
      { word: "Bob Marley", hint: "Rastas" },
      { word: "Shakira", hint: "Caderas" },
      { word: "Beyoncé", hint: "Diva" },
      { word: "Taylor Swift", hint: "Rubia" },
      { word: "Ed Sheeran", hint: "Pelirrojo" },
      { word: "Adele", hint: "Voz" },
      { word: "Rihanna", hint: "Paraguas" },
      { word: "Drake", hint: "Barba" },
      { word: "Eminem", hint: "Rubio" },
      { word: "Kanye West", hint: "Ego" },
      { word: "Bad Bunny", hint: "Gafas" },
      { word: "Daddy Yankee", hint: "Latino" },
      { word: "Rosalía", hint: "Uñas" },
      { word: "Dua Lipa", hint: "Morena" },
      { word: "Bruno Mars", hint: "Bajo" },
      { word: "Lady Gaga", hint: "Rara" },
      { word: "Justin Bieber", hint: "Joven" },
      { word: "Ariana Grande", hint: "Coleta" },
      { word: "The Weeknd", hint: "Pelo" },
      { word: "Coldplay", hint: "Colores" },
      { word: "U2", hint: "Gafas" },
      { word: "Nirvana", hint: "Grunge" },
      { word: "AC/DC", hint: "Rayo" },
      { word: "Metallica", hint: "Negro" },
      { word: "Pink Floyd", hint: "Prisma" },
      { word: "Rolling Stones", hint: "Lengua" },
      { word: "BTS", hint: "Corea" },
      { word: "ABBA", hint: "Suecia" },
      { word: "Elton John", hint: "Gafas" },
      { word: "David Bowie", hint: "Ojos" },
      { word: "Prince", hint: "Morado" },

      // Nuevos artistas
      { word: "Billie Eilish", hint: "Verde" },
      { word: "Harry Styles", hint: "Rizado" },
      { word: "Post Malone", hint: "Tatuajes" },
      { word: "Travis Scott", hint: "Cactus" },
      { word: "Kendrick Lamar", hint: "Rap" },
      { word: "J Balvin", hint: "Colores" },
      { word: "Maluma", hint: "Latino" },
      { word: "Ozuna", hint: "Oso" },
      { word: "Anuel AA", hint: "Real" },
      { word: "Karol G", hint: "Azul" },
      { word: "Becky G", hint: "Reggaeton" },
      { word: "Nicki Minaj", hint: "Rosa" },
      { word: "Cardi B", hint: "Uñas" },
      { word: "Megan Thee Stallion", hint: "Houston" },
      { word: "Doja Cat", hint: "Rosa" },
      { word: "Lil Nas X", hint: "Caballo" },
      { word: "SZA", hint: "R&B" },
      { word: "Frank Ocean", hint: "Rubio" },
      { word: "Tyler The Creator", hint: "Flores" },
      { word: "Pharrell Williams", hint: "Sombrero" },
      { word: "Daft Punk", hint: "Robots" },
      { word: "Deadmau5", hint: "Ratón" },
      { word: "Calvin Harris", hint: "DJ" },
      { word: "David Guetta", hint: "DJ" },
      { word: "Avicii", hint: "Suecia" },
      { word: "Swedish House Mafia", hint: "Tres" },
      { word: "Marshmello", hint: "Blanco" },
      { word: "Skrillex", hint: "Pelo" },
      { word: "Tiësto", hint: "Holandés" },
      { word: "Martin Garrix", hint: "Joven" },
      { word: "Kygo", hint: "Tropical" },
      { word: "Green Day", hint: "Punk" },
      { word: "Blink-182", hint: "Punk" },
      { word: "Linkin Park", hint: "Nu Metal" },
      { word: "Foo Fighters", hint: "Rock" },
      { word: "Red Hot Chili Peppers", hint: "Calcetines" },
      { word: "Guns N' Roses", hint: "Rosa" },
      { word: "Led Zeppelin", hint: "Dirigible" },
      { word: "The Who", hint: "Quien" },
      { word: "Aerosmith", hint: "Labios" },
      { word: "Kiss", hint: "Maquillaje" },
      { word: "Iron Maiden", hint: "Eddie" },
      { word: "Black Sabbath", hint: "Murciélago" },
      { word: "Slipknot", hint: "Máscaras" },
      { word: "System of a Down", hint: "Armenia" },
      { word: "Rage Against the Machine", hint: "Rabia" },
      { word: "Muse", hint: "Espacio" },
      { word: "Arctic Monkeys", hint: "Monos" },
      { word: "Oasis", hint: "Hermanos" },
      { word: "The Cure", hint: "Gótico" },
    ],
  },
  {
    id: 'food',
    name: 'Comida',
    icon: '🍔',
    words: [
      { word: "Pizza", hint: "Horno" },
      { word: "Hamburguesa", hint: "Pan" },
      { word: "Sushi", hint: "Crudo" },
      { word: "Tacos", hint: "Maíz" },
      { word: "Paella", hint: "Arroz" },
      { word: "Pasta", hint: "Agua" },
      { word: "Curry", hint: "Amarillo" },
      { word: "Kebab", hint: "Vertical" },
      { word: "Ramen", hint: "Caldo" },
      { word: "Croissant", hint: "Mantequilla" },
      { word: "Ceviche", hint: "Limón" },
      { word: "Burrito", hint: "Envuelto" },
      { word: "Hot Dog", hint: "Pan" },
      { word: "Tortilla Española", hint: "Huevo" },
      { word: "Gazpacho", hint: "Frío" },
      { word: "Jamón", hint: "Rosa" },
      { word: "Risotto", hint: "Cremoso" },
      { word: "Lasaña", hint: "Capas" },
      { word: "Tiramisú", hint: "Café" },
      { word: "Churros", hint: "Largo" },
      { word: "Helado", hint: "Frío" },
      { word: "Fondue", hint: "Derretido" },
      { word: "Hummus", hint: "Garbanzo" },
      { word: "Guacamole", hint: "Verde" },
      { word: "Croquetas", hint: "Frito" },
      { word: "Patatas Bravas", hint: "Picante" },
      { word: "Nachos", hint: "Crujiente" },
      { word: "Brownie", hint: "Chocolate" },
      { word: "Flan", hint: "Caramelo" },
      { word: "Palomitas", hint: "Maíz" },

      // Nuevas comidas
      { word: "Empanada", hint: "Relleno" },
      { word: "Arepa", hint: "Maíz" },
      { word: "Ceviche", hint: "Limón" },
      { word: "Asado", hint: "Parrilla" },
      { word: "Chimichurri", hint: "Verde" },
      { word: "Poke", hint: "Hawaii" },
      { word: "Dim Sum", hint: "Vapor" },
      { word: "Pad Thai", hint: "Fideos" },
      { word: "Pho", hint: "Vietnam" },
      { word: "Bibimbap", hint: "Arroz" },
      { word: "Kimchi", hint: "Picante" },
      { word: "Gyoza", hint: "Empanadilla" },
      { word: "Tempura", hint: "Frito" },
      { word: "Miso", hint: "Sopa" },
      { word: "Edamame", hint: "Verde" },
      { word: "Wok", hint: "Salteado" },
      { word: "Arroz Frito", hint: "Huevo" },
      { word: "Pollo Tikka", hint: "Rojo" },
      { word: "Naan", hint: "Pan" },
      { word: "Samosa", hint: "Triangular" },
      { word: "Falafel", hint: "Garbanzo" },
      { word: "Shawarma", hint: "Carne" },
      { word: "Baklava", hint: "Miel" },
      { word: "Moussaka", hint: "Berenjena" },
      { word: "Gyros", hint: "Grecia" },
      { word: "Tzatziki", hint: "Yogur" },
      { word: "Carpaccio", hint: "Crudo" },
      { word: "Bruschetta", hint: "Tomate" },
      { word: "Gnocchi", hint: "Patata" },
      { word: "Ravioli", hint: "Relleno" },
      { word: "Carbonara", hint: "Huevo" },
      { word: "Pesto", hint: "Verde" },
      { word: "Focaccia", hint: "Pan" },
      { word: "Calzone", hint: "Cerrado" },
      { word: "Cannoli", hint: "Sicilia" },
      { word: "Panna Cotta", hint: "Crema" },
      { word: "Gelato", hint: "Italia" },
      { word: "Macaron", hint: "Colores" },
      { word: "Crepe", hint: "Fino" },
      { word: "Quiche", hint: "Tarta" },
      { word: "Baguette", hint: "Largo" },
      { word: "Ratatouille", hint: "Verduras" },
      { word: "Bouillabaisse", hint: "Pescado" },
      { word: "Escargot", hint: "Caracol" },
      { word: "Bratwurst", hint: "Alemán" },
      { word: "Pretzel", hint: "Sal" },
      { word: "Waffles", hint: "Cuadros" },
      { word: "Pancakes", hint: "Redondo" },
      { word: "Donut", hint: "Agujero" },
      { word: "Cheesecake", hint: "Queso" },
    ],
  },
  {
    id: 'countries',
    name: 'Países',
    icon: '🌍',
    words: [
      { word: "España", hint: "Sol" },
      { word: "Francia", hint: "Torre" },
      { word: "Italia", hint: "Bota" },
      { word: "Alemania", hint: "Cerveza" },
      { word: "Inglaterra", hint: "Té" },
      { word: "Estados Unidos", hint: "Grande" },
      { word: "Brasil", hint: "Fútbol" },
      { word: "Argentina", hint: "Carne" },
      { word: "México", hint: "Picante" },
      { word: "Japón", hint: "Sushi" },
      { word: "China", hint: "Grande" },
      { word: "India", hint: "Especias" },
      { word: "Australia", hint: "Isla" },
      { word: "Canadá", hint: "Frío" },
      { word: "Rusia", hint: "Grande" },
      { word: "Egipto", hint: "Arena" },
      { word: "Grecia", hint: "Ruinas" },
      { word: "Portugal", hint: "Vecino" },
      { word: "Países Bajos", hint: "Plano" },
      { word: "Suiza", hint: "Montaña" },
      { word: "Suecia", hint: "Frío" },
      { word: "Noruega", hint: "Frío" },
      { word: "Irlanda", hint: "Verde" },
      { word: "Turquía", hint: "Puente" },
      { word: "Tailandia", hint: "Calor" },
      { word: "Corea del Sur", hint: "Tecnología" },
      { word: "Nueva Zelanda", hint: "Ovejas" },
      { word: "Colombia", hint: "Café" },
      { word: "Perú", hint: "Montaña" },
      { word: "Cuba", hint: "Isla" },
      { word: "Jamaica", hint: "Música" },
      { word: "Marruecos", hint: "Desierto" },
      { word: "Kenia", hint: "Safari" },

      // Nuevos países
      { word: "Finlandia", hint: "Sauna" },
      { word: "Dinamarca", hint: "Vikingos" },
      { word: "Bélgica", hint: "Waffles" },
      { word: "Austria", hint: "Mozart" },
      { word: "Polonia", hint: "Vodka" },
      { word: "República Checa", hint: "Cerveza" },
      { word: "Hungría", hint: "Paprika" },
      { word: "Croacia", hint: "Costa" },
      { word: "Eslovenia", hint: "Pequeño" },
      { word: "Rumanía", hint: "Drácula" },
      { word: "Bulgaria", hint: "Yogur" },
      { word: "Serbia", hint: "Balcanes" },
      { word: "Ucrania", hint: "Trigo" },
      { word: "Israel", hint: "Desierto" },
      { word: "Emiratos Árabes", hint: "Dubai" },
      { word: "Arabia Saudita", hint: "Petróleo" },
      { word: "Irán", hint: "Persia" },
      { word: "Pakistán", hint: "Cricket" },
      { word: "Bangladesh", hint: "Ríos" },
      { word: "Vietnam", hint: "Pho" },
      { word: "Filipinas", hint: "Islas" },
      { word: "Indonesia", hint: "Islas" },
      { word: "Malasia", hint: "Torres" },
      { word: "Singapur", hint: "Ciudad" },
      { word: "Nepal", hint: "Everest" },
      { word: "Mongolia", hint: "Caballo" },
      { word: "Kazajistán", hint: "Grande" },
      { word: "Chile", hint: "Largo" },
      { word: "Ecuador", hint: "Mitad" },
      { word: "Bolivia", hint: "Altura" },
      { word: "Paraguay", hint: "Río" },
      { word: "Uruguay", hint: "Pequeño" },
      { word: "Venezuela", hint: "Petróleo" },
      { word: "Costa Rica", hint: "Verde" },
      { word: "Panamá", hint: "Canal" },
      { word: "Guatemala", hint: "Maya" },
      { word: "Honduras", hint: "Caribe" },
      { word: "El Salvador", hint: "Pequeño" },
      { word: "Nicaragua", hint: "Lagos" },
      { word: "República Dominicana", hint: "Caribe" },
      { word: "Puerto Rico", hint: "Isla" },
      { word: "Haití", hint: "Caribe" },
      { word: "Trinidad y Tobago", hint: "Carnaval" },
      { word: "Bahamas", hint: "Islas" },
      { word: "Islandia", hint: "Volcán" },
      { word: "Luxemburgo", hint: "Rico" },
      { word: "Malta", hint: "Isla" },
      { word: "Chipre", hint: "Mediterráneo" },
      { word: "Nigeria", hint: "Petróleo" },
      { word: "Sudáfrica", hint: "Rugby" },
      { word: "Ghana", hint: "Oro" },
      { word: "Senegal", hint: "África" },
    ],
  },
  {
    id: 'animals',
    name: 'Animales',
    icon: '🦁',
    words: [
      { word: "León", hint: "Pelo" },
      { word: "Tigre", hint: "Rayas" },
      { word: "Elefante", hint: "Gris" },
      { word: "Jirafa", hint: "Manchas" },
      { word: "Cebra", hint: "Rayas" },
      { word: "Gorila", hint: "Negro" },
      { word: "Oso Polar", hint: "Blanco" },
      { word: "Oso Panda", hint: "China" },
      { word: "Lobo", hint: "Manada" },
      { word: "Zorro", hint: "Naranja" },
      { word: "Leopardo", hint: "Manchas" },
      { word: "Guepardo", hint: "Rápido" },
      { word: "Cocodrilo", hint: "Verde" },
      { word: "Serpiente", hint: "Largo" },
      { word: "Águila", hint: "Pico" },
      { word: "Búho", hint: "Noche" },
      { word: "Pingüino", hint: "Frío" },
      { word: "Flamenco", hint: "Rosa" },
      { word: "Loro", hint: "Colores" },
      { word: "Tiburón", hint: "Aleta" },
      { word: "Ballena", hint: "Grande" },
      { word: "Delfín", hint: "Salto" },
      { word: "Pulpo", hint: "Ocho" },
      { word: "Tortuga", hint: "Caparazón" },
      { word: "Canguro", hint: "Bolsa" },
      { word: "Koala", hint: "Árbol" },
      { word: "Camello", hint: "Joroba" },
      { word: "Murciélago", hint: "Noche" },
      { word: "Perro", hint: "Fiel" },
      { word: "Gato", hint: "Bigotes" },

      // Nuevos animales
      { word: "Rinoceronte", hint: "Cuerno" },
      { word: "Hipopótamo", hint: "Gordo" },
      { word: "Avestruz", hint: "Grande" },
      { word: "Pavo Real", hint: "Plumas" },
      { word: "Cisne", hint: "Blanco" },
      { word: "Pelícano", hint: "Bolsa" },
      { word: "Tucán", hint: "Pico" },
      { word: "Colibrí", hint: "Pequeño" },
      { word: "Gaviota", hint: "Playa" },
      { word: "Cuervo", hint: "Negro" },
      { word: "Halcón", hint: "Rápido" },
      { word: "Buitre", hint: "Carroña" },
      { word: "Lechuza", hint: "Noche" },
      { word: "Pato", hint: "Agua" },
      { word: "Ganso", hint: "Granja" },
      { word: "Paloma", hint: "Ciudad" },
      { word: "Gorrión", hint: "Pequeño" },
      { word: "Canario", hint: "Amarillo" },
      { word: "Periquito", hint: "Verde" },
      { word: "Iguana", hint: "Verde" },
      { word: "Lagarto", hint: "Escamas" },
      { word: "Camaleón", hint: "Colores" },
      { word: "Gecko", hint: "Pared" },
      { word: "Salamandra", hint: "Fuego" },
      { word: "Sapo", hint: "Verrugas" },
      { word: "Medusa", hint: "Transparente" },
      { word: "Estrella de Mar", hint: "Cinco" },
      { word: "Cangrejo", hint: "Pinzas" },
      { word: "Langosta", hint: "Roja" },
      { word: "Camarón", hint: "Pequeño" },
      { word: "Calamar", hint: "Tinta" },
      { word: "Anguila", hint: "Largo" },
      { word: "Raya", hint: "Plano" },
      { word: "Pez Payaso", hint: "Naranja" },
      { word: "Caballo de Mar", hint: "Raro" },
      { word: "Foca", hint: "Bigotes" },
      { word: "Morsa", hint: "Colmillos" },
      { word: "Nutria", hint: "Agua" },
      { word: "Castor", hint: "Madera" },
      { word: "Ardilla", hint: "Nueces" },
      { word: "Mapache", hint: "Máscara" },
      { word: "Tejón", hint: "Rayas" },
      { word: "Armadillo", hint: "Coraza" },
      { word: "Perezoso", hint: "Lento" },
      { word: "Oso Hormiguero", hint: "Lengua" },
      { word: "Lémur", hint: "Cola" },
      { word: "Orangután", hint: "Naranja" },
      { word: "Chimpancé", hint: "Inteligente" },
      { word: "Mandril", hint: "Colores" },
      { word: "Suricata", hint: "Vigilante" },
      { word: "Hiena", hint: "Risa" },
    ],
  },
  {
    id: 'professions',
    name: 'Profesiones',
    icon: '👨‍⚕️',
    words: [
      { word: "Médico", hint: "Blanco" },
      { word: "Enfermero", hint: "Hospital" },
      { word: "Cirujano", hint: "Manos" },
      { word: "Dentista", hint: "Boca" },
      { word: "Abogado", hint: "Traje" },
      { word: "Juez", hint: "Negro" },
      { word: "Policía", hint: "Azul" },
      { word: "Bombero", hint: "Rojo" },
      { word: "Piloto", hint: "Avión" },
      { word: "Astronauta", hint: "Blanco" },
      { word: "Chef", hint: "Gorro" },
      { word: "Arquitecto", hint: "Planos" },
      { word: "Ingeniero", hint: "Cálculos" },
      { word: "Profesor", hint: "Tiza" },
      { word: "Científico", hint: "Bata" },
      { word: "Periodista", hint: "Micro" },
      { word: "Fotógrafo", hint: "Cámara" },
      { word: "Actor", hint: "Escenario" },
      { word: "Director", hint: "Silla" },
      { word: "Músico", hint: "Notas" },
      { word: "Cantante", hint: "Micro" },
      { word: "Bailarín", hint: "Pies" },
      { word: "Pintor", hint: "Pincel" },
      { word: "Escritor", hint: "Pluma" },
      { word: "Programador", hint: "Código" },
      { word: "Diseñador", hint: "Ratón" },
      { word: "Veterinario", hint: "Animales" },
      { word: "Psicólogo", hint: "Sofá" },
      { word: "Detective", hint: "Lupa" },
      { word: "Cartero", hint: "Cartas" },

      // Nuevas profesiones
      { word: "Mecánico", hint: "Grasa" },
      { word: "Electricista", hint: "Cables" },
      { word: "Fontanero", hint: "Tuberías" },
      { word: "Carpintero", hint: "Madera" },
      { word: "Albañil", hint: "Ladrillos" },
      { word: "Soldador", hint: "Chispas" },
      { word: "Peluquero", hint: "Tijeras" },
      { word: "Maquillador", hint: "Colores" },
      { word: "Sastre", hint: "Aguja" },
      { word: "Zapatero", hint: "Cuero" },
      { word: "Panadero", hint: "Harina" },
      { word: "Carnicero", hint: "Cuchillo" },
      { word: "Pescadero", hint: "Hielo" },
      { word: "Frutero", hint: "Fruta" },
      { word: "Farmacéutico", hint: "Pastillas" },
      { word: "Fisioterapeuta", hint: "Manos" },
      { word: "Nutricionista", hint: "Dieta" },
      { word: "Optometrista", hint: "Ojos" },
      { word: "Podólogo", hint: "Pies" },
      { word: "Logopeda", hint: "Voz" },
      { word: "Traductor", hint: "Idiomas" },
      { word: "Intérprete", hint: "Idiomas" },
      { word: "Bibliotecario", hint: "Libros" },
      { word: "Archivero", hint: "Documentos" },
      { word: "Recepcionista", hint: "Teléfono" },
      { word: "Secretario", hint: "Agenda" },
      { word: "Contable", hint: "Números" },
      { word: "Economista", hint: "Dinero" },
      { word: "Banquero", hint: "Dinero" },
      { word: "Corredor de Bolsa", hint: "Gráficos" },
      { word: "Agente Inmobiliario", hint: "Casas" },
      { word: "Publicista", hint: "Anuncios" },
      { word: "Community Manager", hint: "Redes" },
      { word: "Influencer", hint: "Seguidores" },
      { word: "Youtuber", hint: "Vídeos" },
      { word: "Streamer", hint: "Directo" },
      { word: "Locutor", hint: "Radio" },
      { word: "Presentador", hint: "Televisión" },
      { word: "Cámara", hint: "Vídeo" },
      { word: "Sonidista", hint: "Audio" },
      { word: "Productor", hint: "Cine" },
      { word: "Guionista", hint: "Historia" },
      { word: "Ilustrador", hint: "Dibujo" },
      { word: "Animador", hint: "Movimiento" },
      { word: "Escultor", hint: "Mármol" },
      { word: "Ceramista", hint: "Barro" },
      { word: "Joyero", hint: "Oro" },
      { word: "Relojero", hint: "Hora" },
      { word: "Taxista", hint: "Coche" },
      { word: "Conductor", hint: "Volante" },
      { word: "Capitán", hint: "Barco" },
    ],
  },
  {
    id: 'sports',
    name: 'Deportes',
    icon: '🏆',
    words: [
      { word: "Fútbol", hint: "Once" },
      { word: "Baloncesto", hint: "Alto" },
      { word: "Tenis", hint: "Red" },
      { word: "Golf", hint: "Hoyo" },
      { word: "Béisbol", hint: "Bate" },
      { word: "Rugby", hint: "Ovalado" },
      { word: "Hockey", hint: "Palo" },
      { word: "Voleibol", hint: "Red" },
      { word: "Natación", hint: "Agua" },
      { word: "Atletismo", hint: "Pista" },
      { word: "Ciclismo", hint: "Ruedas" },
      { word: "Boxeo", hint: "Guantes" },
      { word: "Karate", hint: "Blanco" },
      { word: "Judo", hint: "Suelo" },
      { word: "Gimnasia", hint: "Flexible" },
      { word: "Patinaje", hint: "Hielo" },
      { word: "Esquí", hint: "Nieve" },
      { word: "Surf", hint: "Olas" },
      { word: "Escalada", hint: "Roca" },
      { word: "Maratón", hint: "Largo" },
      { word: "Triatlón", hint: "Tres" },
      { word: "MMA", hint: "Jaula" },
      { word: "Esgrima", hint: "Espada" },
      { word: "Polo", hint: "Caballo" },
      { word: "Cricket", hint: "Bate" },
      { word: "Fútbol Americano", hint: "Casco" },
      { word: "Balonmano", hint: "Mano" },
      { word: "Ajedrez", hint: "Tablero" },
      { word: "Dardos", hint: "Diana" },
      { word: "Billar", hint: "Verde" },

      // Nuevos deportes
      { word: "Waterpolo", hint: "Piscina" },
      { word: "Piragüismo", hint: "Remo" },
      { word: "Remo", hint: "Agua" },
      { word: "Vela", hint: "Viento" },
      { word: "Windsurf", hint: "Viento" },
      { word: "Kitesurf", hint: "Cometa" },
      { word: "Wakeboard", hint: "Lancha" },
      { word: "Esquí Acuático", hint: "Agua" },
      { word: "Buceo", hint: "Profundo" },
      { word: "Snorkel", hint: "Tubo" },
      { word: "Snowboard", hint: "Tabla" },
      { word: "Bobsled", hint: "Hielo" },
      { word: "Luge", hint: "Trineo" },
      { word: "Skeleton", hint: "Cabeza" },
      { word: "Curling", hint: "Piedra" },
      { word: "Hockey sobre Hielo", hint: "Disco" },
      { word: "Patinaje Artístico", hint: "Salto" },
      { word: "Patinaje de Velocidad", hint: "Rápido" },
      { word: "Biatlón", hint: "Disparo" },
      { word: "Salto de Esquí", hint: "Vuelo" },
      { word: "Freestyle", hint: "Trucos" },
      { word: "BMX", hint: "Bici" },
      { word: "Motocross", hint: "Barro" },
      { word: "Rally", hint: "Tierra" },
      { word: "Fórmula 1", hint: "Velocidad" },
      { word: "NASCAR", hint: "Óvalo" },
      { word: "MotoGP", hint: "Moto" },
      { word: "Karting", hint: "Pequeño" },
      { word: "Automovilismo", hint: "Circuito" },
      { word: "Halterofilia", hint: "Pesas" },
      { word: "Crossfit", hint: "Intenso" },
      { word: "Powerlifting", hint: "Fuerza" },
      { word: "Culturismo", hint: "Músculos" },
      { word: "Calistenia", hint: "Peso" },
      { word: "Yoga", hint: "Flexible" },
      { word: "Pilates", hint: "Core" },
      { word: "Aeróbic", hint: "Música" },
      { word: "Zumba", hint: "Baile" },
      { word: "Spinning", hint: "Bici" },
      { word: "Parkour", hint: "Saltar" },
      { word: "Skateboard", hint: "Tabla" },
      { word: "Roller", hint: "Ruedas" },
      { word: "Lacrosse", hint: "Red" },
      { word: "Squash", hint: "Pared" },
      { word: "Bádminton", hint: "Pluma" },
      { word: "Ping Pong", hint: "Mesa" },
      { word: "Pádel", hint: "Cristal" },
      { word: "Frontón", hint: "Pared" },
      { word: "Pelota Vasca", hint: "Cesta" },
      { word: "Petanca", hint: "Bolas" },
      { word: "Bolos", hint: "Pinos" },
    ],
  },
];

export function getRandomWord(mode: 'classic' | 'withHint' | 'categories', categoryId?: string): CategoryWord {
  // Import dynamically to avoid SSR issues
  const { filterUnplayedWords, markWordAsPlayed } = require('./game-history');

  if (mode === 'categories' && categoryId) {
    const category = CATEGORIES.find(c => c.id === categoryId);
    if (category && category.words.length > 0) {
      // Filter out played words
      const unplayedWords = filterUnplayedWords(category.words);
      const selectedWord = unplayedWords[Math.floor(Math.random() * unplayedWords.length)];
      markWordAsPlayed(selectedWord.word);
      return selectedWord;
    }
  }

  // Para classic y withHint usamos las palabras generales
  const unplayedWords = filterUnplayedWords(GENERAL_WORDS);
  const selectedWord = unplayedWords[Math.floor(Math.random() * unplayedWords.length)];
  markWordAsPlayed(selectedWord.word);
  return selectedWord;
}

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find(c => c.id === id);
}
